version: 2

sources:
  - name: Stage1CUpp
    schema: Stage1CUpp
    tables:
      - name: "С_Номенклатура" 
      - name: "С_СерииНоменклатуры"
      - name: "РС_ЗначенияСвойствОбъектов"
      - name: "РН_Продажи"
      - name: "РН_ТоварыНаСкладахОстатки"
      - name: "РС_Штрихкоды"