version: 2

sources:
  - name: analytics_shipments
    schema: analytics_shipments
    tables:
      - name: calendar2
      - name: nbrb_exrates 

  - name: Stage1CUpp
    schema: Stage1CUpp
    tables:
      - name: "РС_ЗначенияСвойствОбъектов"
      - name: "Д_ЗаказПокупателя"
      - name: "С_Номенклатура" 
      - name: "РН_Продажи"
      - name: "РН_ТоварыНаСкладахОстатки"
      - name: "С_ТорговыеОбъекты"
      - name: "Д_РеализацияТоваровУслуг"
      - name: "С_Контрагенты"
      - name: "Д_ВозвратТоваровОтПокупателя"
      - name: "РС_Штрихкоды"
      - name: "Д_РеализацияТоваровУслугТовары"
        description: "Табличная часть с товарами документов \"РеализацияТоваровУслуг\". Наполняет РН_Продажи"
      - name: "РН_ВыпускПродукции"
      - name: "С_НоменклатурныеГруппы"
      - name: "С_Склады"
      - name: "Д_ПланПроизводства"
      - name: "С_СерииНоменклатуры"
      - name: "С_Регионы"

models:
  - name: "stg_C_ТорговыеОбъекты"
    description: "Актуальные торговые объекты из 1С"
    columns:
     - name: "СсылкаГуид"
       description: "Гуид объекта"
       data-tests:
        - not_null
        - unique
        