version: 2

sources:
  - name: analytics_shipments
    schema: analytics_shipments
    tables:
      - name: calendar2
      - name: nbrb_exrates 

  - name: Stage1CUpp
    schema: Stage1CUpp
    tables:
      - name: "РС_ЗначенияСвойствОбъектов"
      - name: "Д_ЗаказПокупателя"
      - name: "С_Номенклатура" 
      - name: "РН_Продажи"
      - name: "РН_ТоварыНаСкладахОстатки"
      - name: "С_ТорговыеОбъекты"
      - name: "Д_РеализацияТоваровУслуг"
      - name: "С_Контрагенты"
      - name: "Д_ВозвратТоваровОтПокупателя"
      - name: "РС_Штрихкоды"
      - name: "Д_РеализацияТоваровУслугТовары"
      - name: "РН_ВыпускПродукции"
      - name: "С_НоменклатурныеГруппы"
      - name: "С_Склады"
      - name: "Д_ПланПроизводства"