version: 2

models:
  - name: subdim_Общие_наименования
    description: "Таблица с общими наименованиями продуктов"
  
  - name: subdim_Штрихкоды
    description: "Справочник штрихкодов"

  - name: dim_nomenclature
    description: "Таблица фактов продаж"

  - name: subdim_С_НоменклатурныеГруппы
    description: "Таблица с номенклатурными группами. Пример: \"Детское питание\", \"Десткое питание: гуалапак\""

  - name: dim_calendar
    description: "Календарь"

  - name: subdim_nbrb_exrate_USD
    description: "Курс обмена НБ РБ USD"
  
  - name: subdim_nbrb_exrate_EUR
    description: "Курс обмена НБ РБ EUR"

  - name: subdim_nbrb_exrate_RUB
    description: "Курс обмена НБ РБ RUB"
    


