version: 2

models:

  - name: sub_dim_Общие_наименования
    description: "Таблица с общими наименованиями продуктов"
  
  - name: sub_dim_Штрихкоды
    description: "Справочник штрихкодов"

  - name: dim_nomenclature
    description: "Таблица фактов продаж"

  - name: subdim_stg_С_НоменклатурныеГруппы
    description: "Таблица с номенклатурными группами. Пример: \"Детское питание\", \"Десткое питание: гуалапак\""


